### ISSUE TITLE
Rotation for random w

### ISSUE THREAD

**Issue by a7b23** [ali-design/gan_steerability#6]
Hi, I trained my own model for zoom transformation and I wanted to check the output images for the model at checkpoint-0. Strangely I find the images to still exhibit rotation even though this checkpoint is supposed to be random. Attached is the image for that. Can you please explain the reasoning behind this?
![image](https://user-images.githubusercontent.com/12389081/79080119-1e303280-7cc8-11ea-8e5d-df38e5644165.png)

**Comment by chail** [comment]
Hi, in the current code the first checkpoint is saved after training for a fraction of the samples (governed by the `--model_save_freq` option (rather than no training at all), so the first checkpoint saved should already have a slightly trained effect. So unless you modified the code otherwise, that might be why you are observing this small effect.
