### ISSUE TITLE
Errors when pulling resources "bash resources/download_resources.sh"

### ISSUE THREAD

**Issue by CorpusCallosum** [ali-design/gan_steerability#7]
Hi, I'm trying to run this sample code, but got stuck on this step:

> Download resources:
> we provide a script for downloading associated resources (e.g. stylegan). Fetch these by running:
> `bash resources/download_resources.sh`

When I run this script I'm getting a few errors:

```
sudo bash resources/download_resources.sh
Downloading resources to directory ... resources
resources/download_resources.sh: line 9: wget: command not found
tar: Error opening archive: Failed to open 'resources/ssd_mobilenet_v1_coco_2017_11_17.tar.gz'
resources/download_resources.sh: line 14: wget: command not found
chmod: resources/fid.py: No such file or directory
fatal: destination path 'stylegan' already exists and is not an empty directory.
mv: rename ./stylegan to resources/stylegan: Directory not empty
fatal: destination path 'lpips-tensorflow' already exists and is not an empty directory.
mv: rename ./lpips-tensorflow to resources/lpips-tensorflow: Directory not empty
Cloning into 'progressive_growing_of_gans'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
mv: rename ./progressive_growing_of_gans to resources/progressive_growing_of_gans: No such file or directory
mkdir: resources/pgan_pretrained: File exists
resources/download_resources.sh: line 32: gdown: command not found
```

I tried installing wget, but the error keeps happening. 

By the way I am on a Mac OSX Catalina v10.15.7

I am not sure if this project will run on a Mac, since it is technically UNIX, not Linux?

Thanks - Jack

**Comment by chail** [comment]
hmm, it looks like wget is failing and parts of the script executed previously (and so are failing as you run it a second time). Since you are developing locally, you could also just open a browser, and download the file specified at each link rather than running wget, and move it to the `resources/` directory. 

[maybe the easiest solution] I haven't tested it on MAC personally, but we provide some [Colab links](https://colab.research.google.com/drive/1kn6yG8PqD1U2bUcy32V1iAVjzlcQWcG3) where you can test it out in the browser without running anything locally!
